## Importing

In [17]:
import pandas as pd
import numpy as np

Employees = pd.read_excel("../Employees.xlsx")

# **Final Questions**
1. Which department has the highest average performance?
2. Which department has the highest salary?
3. Which education level performs best?
4. Which age group performs best?
5. Is attendance related to performance?
6. Do more projects always improve performance?
7. Which variables have the strongest positive correlation?
8. Which variables have the strongest negative correlation?
9. Which visualization provided the most useful insight?
10. Which preprocessing step improved data quality the most?
11. Identify three important patterns.
12. Provide five evidence-based recommendations

### **1. Which department has the highest average performance?**

In [5]:
department_performance = (
    Employees.groupby("Department")["Performance Score"]
    .mean()
    .sort_values(ascending=False)
)

print(department_performance)

Department
HR             56.493119
Sales          55.708315
Finance        55.699009
Engineering    55.653678
Marketing      54.714712
Name: Performance Score, dtype: float64

#### **Answer: 1** HR

### **2. Which department has the highest salary?**

In [6]:
department_salary = (
    Employees.groupby("Department")["Salary"]
    .mean()
    .sort_values(ascending=False)
)

print(department_salary)

Department
Engineering    84614.563218
Finance        79293.720721
Marketing      67815.826923
Sales          65094.820225
HR             63469.018349
Name: Salary, dtype: float64

#### **Answer: 2** Engineering

### **3. Which education level performs best?**

In [7]:
education_performance = (
    Employees.groupby("Education")["Performance Score"]
    .mean()
    .sort_values(ascending=False)
)

print(education_performance)

Education
PhD            62.774000
Master's       57.492921
Bachelor's     53.641728
High School    36.292000
Name: Performance Score, dtype: float64

#### **Answer 3:** PhD

### **4. Which age group performs best?**

In [12]:
age_performance = (
    Employees.groupby("Age")["Performance Score"]
    .mean()
    .sort_values(ascending=False)
)

print(age_performance)

Age
60.000000    67.405000
63.000000    65.060000
51.000000    64.575556
58.000000    63.661429
56.000000    61.540909
64.000000    61.246154
59.000000    60.214545
55.000000    59.937333
41.298387    59.785000
57.000000    59.652222
54.000000    59.594667
53.000000    59.511818
62.000000    59.473077
44.000000    59.393333
40.000000    58.830000
61.000000    58.810909
43.000000    57.243077
49.000000    56.492667
41.000000    56.424167
45.000000    56.341667
52.000000    56.105000
37.000000    55.982143
48.000000    55.292727
39.000000    54.595000
47.000000    54.413000
36.000000    54.135833
46.000000    54.112500
34.000000    53.896000
42.000000    53.398750
29.000000    53.375556
23.000000    53.220000
28.000000    53.040000
50.000000    53.001667
30.000000    52.436000
22.000000    52.211429
24.000000    52.006250
18.000000    51.884286
25.000000    51.498750
38.000000    51.436364
32.000000    51.422727
33.000000    51.046667
35.000000    50.831111
20.000000    50.647500
19.000000    50.546250
27.000000    50.180833
31.000000    49.866667
26.000000    48.662000
21.000000    46.873333
Name: Performance Score, dtype: float64

#### **Answer: 4** 50-60

### **5. Is attendance related to performance?**

In [13]:
Employees[["Attendance Rate", "Performance Score"]].corr()

                   Attendance Rate  Performance Score
Attendance Rate           1.000000           0.300629
Performance Score         0.300629           1.000000

#### **Answer 5:** Yes

### **6. Do more projects always improve performance?**

In [14]:
Employees[["Projects Completed", "Performance Score"]].corr()

                    Projects Completed  Performance Score
Projects Completed            1.000000           0.715252
Performance Score             0.715252           1.000000

#### **Answer 6:** Yes

### **7. Which variables have the strongest positive correlation?**

In [18]:
corr = Employees.corr(numeric_only=True)

strongest_positive = (
    corr.where(~np.eye(corr.shape[0], dtype=bool))
        .stack()
        .sort_values(ascending=False)
)

print(strongest_positive.head())

Projects Completed  Experience            0.960219
Experience          Projects Completed    0.960219
Performance Score   HighPerformer         0.784141
HighPerformer       Performance Score     0.784141
Performance Score   Experience            0.739259
dtype: float64

#### **Answer:** 
Experience - ProjectsCompleted <br>
Experience - Performance Score <br>
...

### **8. Which variables have the strongest negative correlation?**

In [19]:
strongest_negative = (
    corr.where(~np.eye(corr.shape[0], dtype=bool))
        .stack()
        .sort_values()
)

print(strongest_negative.head())

Experience          Training Hours       -0.384208
Training Hours      Experience           -0.384208
                    Projects Completed   -0.374819
Projects Completed  Training Hours       -0.374819
Age                 Training Hours       -0.336290
dtype: float64

#### **Answer:** 
TrainingHours - Experience <br>
TrainingHours - Age <br>
...

### **9. Which visualization provided the most useful insight?**

#### **Answer:** 
The correlation heatmap provided the most useful insight because it summarized the relationships between all numerical variables in a single visualization

### **10. Which preprocessing step improved data quality the most?**

#### **Answer:** 
Filling missing values using logical relationships (for example, inferring Department from Job Title and recalculating Performance Score from its underlying variables) improved the dataset the most. This preserved realistic relationships instead of relying on simple statistical imputation.

### **11. Identify three important patterns.**

In [25]:
Employees[["Attendance Rate", "Performance Score"]].corr()

                   Attendance Rate  Performance Score
Attendance Rate           1.000000           0.300629
Performance Score         0.300629           1.000000

In [31]:
print(Employees.groupby("Education")[
    "Performance Score"
].mean())

# print(Employees[["EducationLevel", "Performance Score"]].corr())

Education
Bachelor's     53.641728
High School    36.292000
Master's       57.492921
PhD            62.774000
Name: Performance Score, dtype: float64

In [28]:
Employees[["Experience", "Salary"]].corr()

            Experience    Salary
Experience    1.000000  0.673708
Salary        0.673708  1.000000

#### **Answer:** 
1. Higher attendance rates are associated with better performance scores.
2. Higher education levels tend to have higher average salaries and performance scores.
3. Employees with more experience generally earn higher salaries.

### **12. Provide five evidence-based recommendations.**

#### **Answer:** 
1. Increase employee training hours to improve overall performance.
2. Encourage higher attendance through flexible work policies and incentives.
3. Invest in employee development and education programs.
4. Review salary structures regularly to ensure they reflect experience and performance.
5. Focus retention efforts on high-performing employees through recognition, career growth, and bonus programs.